### ISSUE TITLE
CMS vs Adding Data Via Git

### ISSUE THREAD

**Issue by sunscreem** [sunscreem/dogpubtimemachine#27]
@billythekid Lets say I need a way to add a new bar to the app.

There's two options.

1. Build a quick basic CMS
2. Hard code the updates as `fixtures` here.

The obvious thing is 1. Nice and easy.. laravel basic auth, basic form etc.

The things is, without getting all fancy, there's then no easy to way for me to approve any changes.

For example - you spot a new bar is opening, so you log in and add it. 

It would be nice to have a peer review step thrown in there?

Option 2, where we require any new data added via, say, a PR, using the fixtures pattern. 

That way I/we have full control of anything changing? Since its likely to be only me and you editing content would that make sense?

Before you answer - consider that one of the ideas on the to-do list is the ability to tag beers with different styles. That's a lot of beers and a lot of tags.

**Comment by billythekid** [comment]
I'm leaning towards fixtures but I can see how a form could be handy. I actually think that in future we probably don't want to be seeding or migrating all the time, especially for edits. Also, could handle relationships better with a form I reckon.

Yeah, just talked myself round there didn't I? lol
